** 图片处理
所有图片都存放在 =./img= 目录下，这些图片最终都会被 push 到 github 上。因此，图片采用 https 链接的形式给出，首部固定为

#+BEGIN_SRC c
https://raw.githubusercontent.com/Ynjxsjmh/ynjxsjmh.github.io/master/img/
#+END_SRC

剩余部分根据图片具体路径填上，这里的年份文件夹有时老忘写...

*** 图片名称含义
一个图片名称样例是 =2018-08-03-01-01=

前 3 部分是文章日期，中间一个是该日期中的第几篇文章，最后是这篇文章中的第几幅图片。

当然一些文章中的图片是按图片含义来组织的文件名。

** org 文件形成
因为有一部分的文章先前是在 CSDN 的编辑器上完成，而一开始我使用的是 *富文本编辑器* ，后来才学会 Markdown 进而使用 *Markdown 编辑器* 。

对于这部分的文章：
- *富文本编辑器* 写的文章直接改成 org 文件
- *Markdown 编辑器* 写的文章先修改成 origin.md 文件，再使用 pandoc 转化成 org 文件。最后使用 ox-gfm 的 =org-gfm-export-as-markdown= [fn:1] 将 org 文件转化成 md 文件。这样做的原因是使用 ox-gfm 转化成的 md 文件带目录，可能有其他的方式，以后找找。

使用 ox-gfm 转化后数学公式 $ 会被替换成 \(，$$ 会被替换成 \{。得用自己写的函数 =brackets-to-dollar= 重新转成美元符。

使用 pandoc 将 md 转化为 org 后，org 换行会出错。不过因为 =#OPTIONS= 设置了 =\n:nil= ，因此是以空行来表示换行的，所以换行不必多费心。唯一需要注意的一点是列表会出错，需要修改。

使用 ox-gfm 将 org 转化为 md 时，首先要执行一下 =org-reload= 才能正常使用其功能。

最后将修改好的 md 文件复制到 =./_post= 目录下，再使用 =jekyll serve= 或 =jekyll s= 命令就可以在浏览器中预览了。

* 策略转变
因为博客是Markdown语法，org转到md还要进行一些格式调整，十分的费时间。所以以后写文章干脆直接用Markdown写了。

[fn:1] 如果出现 =org-export-barf-if-invalid-backend: Unknown "nil" back-end: Aborting export= 错误，执行一下 =C-u M-x org-reload=